"use strict";
const state={wines:[],search:"",sort:"name",filters:{},view:"grid"};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const typeLabels={red:"레드",white:"화이트",sparkling:"스파클링",rose:"로제",dessert:"디저트"};
const text=(v,f="-")=>v===null||v===undefined||v===""?f:String(v);
const escapeHtml=v=>text(v,"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const assetUrl=p=>p?new URL(String(p).replace(/^\/+/,""),document.baseURI).href:null;
const money=v=>v===null||v===undefined?"-":new Intl.NumberFormat("ko-KR",{style:"currency",currency:"KRW",maximumFractionDigits:0}).format(v);
const inventory=w=>w.purchases.reduce((n,p)=>n+p.quantity,0)-w.consumptions.reduce((n,c)=>n+c.quantity,0);
const latest=(items,key="date")=>[...items].sort((a,b)=>String(b[key]).localeCompare(String(a[key])))[0]??null;
const latestRating=w=>latest(w.consumptions.filter(c=>c.review?.rating!=null))?.review?.rating??null;
const stars=r=>r==null?"-":`<span class="stars">${"★".repeat(Math.round(r))}${"☆".repeat(Math.max(0,5-Math.round(r)))}</span> ${r}`;
function imageMarkup(w,klass="") { const name=w.wine.name.ko||w.wine.name.en,url=assetUrl(w.wine.image); return url?`<img class="${klass}" src="${escapeHtml(url)}" alt="${escapeHtml(name)} 병" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="empty-bottle" hidden><span></span></div>`:`<div class="empty-bottle ${klass}"><span></span></div>`; }
function latestPurchase(w){return latest(w.purchases)}
function updateStats(){const ws=state.wines;const owned=ws.reduce((n,w)=>n+inventory(w),0);$("#stat-owned").textContent=owned;$("#stat-wines").textContent=ws.filter(w=>inventory(w)>0).length;$("#stat-consumed").textContent=ws.reduce((n,w)=>n+w.consumptions.reduce((x,c)=>x+c.quantity,0),0);$("#stat-total").textContent=money(ws.reduce((n,w)=>n+w.purchases.reduce((x,p)=>x+(p.price.amount??0)*p.quantity,0),0));}
function values(get){return [...new Set(state.wines.flatMap(get).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),"ko"));}
function populateFilters(){const cfg={type:w=>[w.wine.type],country:w=>[w.wine.country],region:w=>[w.wine.region],winery:w=>[w.wine.winery],grape:w=>w.wine.grapes};Object.entries(cfg).forEach(([key,get])=>values(get).forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=key==="type"?(typeLabels[v]??v):v;$(`[data-filter="${key}"]`).append(o)}));}
function matches(w){const q=state.search.trim().toLocaleLowerCase("ko"),x=[w.wine.name.ko,w.wine.name.en,w.wine.winery].filter(Boolean).join(" ").toLocaleLowerCase("ko"),f=state.filters;if(q&&!x.includes(q))return false;return(!f.type||w.wine.type===f.type)&&(!f.country||w.wine.country===f.country)&&(!f.region||w.wine.region===f.region)&&(!f.winery||w.wine.winery===f.winery)&&(!f.grape||w.wine.grapes.includes(f.grape))&&(!f.owned||(f.owned==="yes"?inventory(w)>0:inventory(w)===0));}
function nullable(a,b,d=1){const am=a==null||a==="",bm=b==null||b==="";if(am&&bm)return 0;if(am)return 1;if(bm)return-1;return(a>b?1:a<b?-1:0)*d}
function sorted(ws){const s={name:(a,b)=>a.wine.name.en.localeCompare(b.wine.name.en,"ko"),"purchase-desc":(a,b)=>nullable(latestPurchase(a)?.date,latestPurchase(b)?.date,-1),"price-desc":(a,b)=>nullable(latestPurchase(a)?.price.amount,latestPurchase(b)?.price.amount,-1),"price-asc":(a,b)=>nullable(latestPurchase(a)?.price.amount,latestPurchase(b)?.price.amount),"rating-desc":(a,b)=>nullable(latestRating(a),latestRating(b),-1)};return [...ws].sort(s[state.sort]??s.name)}
function card(w){const x=w.wine,p=latestPurchase(w),name=x.name.ko||x.name.en;return `<button class="wine-card" data-id="${escapeHtml(w.id)}"><div class="card-image">${imageMarkup(w)}<span class="card-status">${inventory(w)>0?`보유 ${inventory(w)}병`:"소비 완료"}</span></div><div class="card-body"><p class="card-kicker">${escapeHtml(x.winery)}</p><h3>${escapeHtml(name)}</h3>${x.name.ko?`<p class="english-name">${escapeHtml(x.name.en)}</p>`:""}<div class="card-facts"><span>${escapeHtml([x.country,x.region].filter(Boolean).join(" · "))}</span><span>${escapeHtml(typeLabels[x.type]??x.type)}</span>${x.vintage?`<span>${x.vintage}</span>`:""}</div><div class="card-footer"><div><span>최근 구매가</span><strong>${money(p?.price.amount)}</strong></div><div class="rating"><span>최근 내 평점</span><strong>${stars(latestRating(w))}</strong></div></div></div></button>`}
function list(w){const x=w.wine,p=latestPurchase(w),name=x.name.ko||x.name.en;return `<button class="wine-list-item" data-id="${escapeHtml(w.id)}"><div class="list-image">${imageMarkup(w)}</div><div class="list-main"><h3>${escapeHtml(name)}</h3><p>${escapeHtml(x.winery)}</p></div><div><span>타입</span><strong>${escapeHtml(typeLabels[x.type]??x.type)}</strong></div><div><span>보유</span><strong>${inventory(w)}병</strong></div><div><span>최근 구매가</span><strong>${money(p?.price.amount)}</strong></div></button>`}
function render(){const ws=sorted(state.wines.filter(matches));$("#result-count").textContent=`${ws.length} bottles`;$("#card-grid").innerHTML=ws.map(state.view==="grid"?card:list).join("");$("#card-grid").className=state.view==="grid"?"card-grid":"list-view";$("#empty-state").hidden=state.wines.length!==0;$("#no-results").hidden=state.wines.length===0||ws.length!==0;$("#card-grid").hidden=ws.length===0;$$("[data-id]",$("#card-grid")).forEach(e=>e.onclick=()=>openDetail(e.dataset.id));}
const row=(l,v,wide=false,raw=false)=>`<div${wide?' class="wide"':""}><dt>${l}</dt><dd>${raw?v:escapeHtml(v)}</dd></div>`;
function history(items,kind){if(!items.length)return "<p class=\"muted\">기록 없음</p>";return `<div class="history">${[...items].sort((a,b)=>b.date.localeCompare(a.date)).map(i=>`<article><strong>${i.date} · ${i.quantity}병</strong><span>${escapeHtml(kind==="purchase"?`${text(i.store)} · ${money(i.price.amount)}`:text(i.note))}</span>${kind==="purchase"&&i.note?`<small>${escapeHtml(i.note)}</small>`:""}${i.review?`<div class="review"><b>${stars(i.review.rating)}</b><strong>${escapeHtml(text(i.review.title))}</strong>${i.review.content!==null?`<p>${escapeHtml(i.review.content)}</p>`:""}</div>`:""}</article>`).join("")}</div>`}
function openDetail(id){const w=state.wines.find(x=>x.id===id);if(!w)return;const x=w.wine,name=x.name.ko||x.name.en;$("#detail-content").innerHTML=`<div class="detail-hero"><div class="detail-image">${imageMarkup(w)}</div><div class="detail-summary"><p class="card-kicker">${escapeHtml(x.winery)}</p><h2 id="detail-title">${escapeHtml(name)}</h2>${x.name.ko?`<p class="english-name">${escapeHtml(x.name.en)}</p>`:""}<dl class="detail-specs">${row("TYPE",typeLabels[x.type]??x.type)}${row("INVENTORY",`${inventory(w)}병`)}${row("VINTAGE",text(x.vintage))}${row("ALCOHOL",x.alcohol!=null?`${x.alcohol}%`:"-")}</dl></div></div><div class="detail-sections"><section><h3>Wine</h3><dl>${row("와이너리",text(x.winery))}${row("국가",text(x.country))}${row("지역",text(x.region))}${row("품종",x.grapes.join(", ")||"-")}${row("용량",x.volumeMl?`${x.volumeMl} ml`:"-")}${row("Vivino 평점",x.vivino.rating!=null?`${x.vivino.rating} (${text(x.vivino.ratingCount)} ratings)`:"-")}${row("Vivino 링크",x.vivino.url?`<a href="${escapeHtml(x.vivino.url)}" target="_blank" rel="noreferrer">열기</a>`:"-",true,true)}</dl></section><section><h3>Purchase history</h3>${history(w.purchases,"purchase")}</section><section class="wide-section"><h3>Consumption & Review</h3>${history(w.consumptions,"consumption")}</section></div>`;$("#detail-dialog").showModal();}
function filters(){const n=Object.values(state.filters).filter(Boolean).length;$("#filter-count").textContent=n;$("#filter-count").hidden=!n}
function bind(){ $$('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;localStorage.setItem("wineCollectionView",state.view);$$('[data-view]').forEach(q=>q.setAttribute("aria-pressed",q===b));render()});$("#search-input").oninput=e=>{state.search=e.target.value;render()};$("#sort-select").onchange=e=>{state.sort=e.target.value;render()};$("#filter-toggle").onclick=()=>{const p=$("#filter-panel");p.hidden=!p.hidden;$("#filter-toggle").setAttribute("aria-expanded",!p.hidden)};$$('[data-filter]').forEach(s=>s.onchange=e=>{state.filters[e.target.dataset.filter]=e.target.value;filters();render()});$("#reset-filters").onclick=$("#reset-search").onclick=()=>{state.search="";state.filters={};$("#search-input").value="";$$('[data-filter]').forEach(s=>s.value="");filters();render()};$("#dialog-close").onclick=()=>$("#detail-dialog").close();document.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search-input").focus()}}}
async function load(){try{const r=await fetch(assetUrl("data/wines.json"),{cache:"no-store"});if(!r.ok)throw Error(r.status);state.wines=await r.json();if(!Array.isArray(state.wines))throw Error("Invalid JSON");state.view=localStorage.getItem("wineCollectionView")==="list"?"list":"grid";$$('[data-view]').forEach(b=>b.setAttribute("aria-pressed",b.dataset.view===state.view));updateStats();populateFilters();render();$("#as-of").textContent=`총 ${state.wines.length}개의 기록`}catch(e){console.error(e);$("#error-state").hidden=false}finally{$("#loading-state").hidden=true}}
bind();load();
