"use strict";
const state={wines:[],search:"",sort:"name",filters:{type:"",owned:"yes"},view:"grid"};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const typeLabels={red:"레드",white:"화이트",sparkling:"스파클링",rose:"로제",dessert:"디저트",fortified:"주정강화",orange:"오렌지",other:"기타"};
const bottleSizeLabels={half:"Half",standard:"Standard",magnum:"Magnum","double-magnum":"Double Magnum",other:"Other"};
const quickFilterOrder=["red","white","sparkling","rose","orange","dessert","fortified","other"];
const quickFilterLabels={red:"Red",white:"White",sparkling:"Sparkling",rose:"Rosé",orange:"Orange",dessert:"Dessert",fortified:"Fortified",other:"Other"};
const text=(v,f="-")=>v===null||v===undefined||v===""?f:String(v);
const escapeHtml=v=>text(v,"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const assetUrl=p=>p?new URL(String(p).replace(/^\/+/,""),document.baseURI).href:null;
const money=v=>v===null||v===undefined?"-":new Intl.NumberFormat("ko-KR",{style:"currency",currency:"KRW",maximumFractionDigits:0}).format(v);
const inventory=w=>w.purchases.reduce((n,p)=>n+p.quantity,0)-w.consumptions.reduce((n,c)=>n+c.quantity,0);
const latest=(items,key="date")=>[...items].sort((a,b)=>String(b[key]).localeCompare(String(a[key])))[0]??null;
const latestRating=w=>latest(w.consumptions.filter(c=>c.review?.rating!=null))?.review?.rating??null;
const stars=r=>r==null?"-":`<span class="stars">${"★".repeat(Math.round(r))}${"☆".repeat(Math.max(0,5-Math.round(r)))}</span> ${r}`;
const vintageLabel=x=>x.vintage!=null?String(x.vintage):x.isNonVintage===true?"NV":null;
const readableBottleSize=size=>bottleSizeLabels[size]??String(size).replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const specialBottleSize=x=>{const size=x.bottle?.size;return size&&size!=="standard"&&size!=="other"?readableBottleSize(size):null};
const wineIdentifiers=x=>{const vintage=vintageLabel(x),size=specialBottleSize(x);return vintage||size?`<div class="wine-identifiers">${vintage?`<span class="vintage-badge">${escapeHtml(vintage)}</span>`:""}${size?`<span class="bottle-size-badge">${escapeHtml(size)}</span>`:""}</div>`:""};
function imageMarkup(w,klass="") { const name=w.wine.name.ko||w.wine.name.en,url=assetUrl(w.wine.image); return url?`<img class="${klass}" src="${escapeHtml(url)}" alt="${escapeHtml(name)} 병" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="empty-bottle" hidden><span></span></div>`:`<div class="empty-bottle ${klass}"><span></span></div>`; }
function latestPurchase(w){return latest(w.purchases)}
function updateStats(){const ws=state.wines;const owned=ws.reduce((n,w)=>n+inventory(w),0);$("#stat-owned").textContent=owned;$("#stat-wines").textContent=ws.filter(w=>inventory(w)>0).length;$("#stat-consumed").textContent=ws.reduce((n,w)=>n+w.consumptions.reduce((x,c)=>x+c.quantity,0),0);$("#stat-total").textContent=money(ws.reduce((n,w)=>n+w.purchases.reduce((x,p)=>x+(p.price.amount??0)*p.quantity,0),0));}
function values(get){return [...new Set(state.wines.flatMap(get).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),"ko"));}
function populateFilters(){const cfg={country:w=>[w.wine.country],region:w=>[w.wine.region],winery:w=>[w.wine.winery],grape:w=>w.wine.grapes};Object.entries(cfg).forEach(([key,get])=>values(get).forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;$(`[data-filter="${key}"]`).append(o)}));}
function populateQuickFilters(){const types=[...new Set(state.wines.map(w=>w.wine.type).filter(Boolean))].sort((a,b)=>{const ai=quickFilterOrder.indexOf(a),bi=quickFilterOrder.indexOf(b);return(ai<0?Infinity:ai)-(bi<0?Infinity:bi)||a.localeCompare(b,"en")});const label=t=>quickFilterLabels[t]??t.replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());$(".type-quick-filters").innerHTML=`<button type="button" data-type="" aria-pressed="true">전체</button>${types.map(t=>`<button type="button" data-type="${escapeHtml(t)}" aria-pressed="false">${escapeHtml(label(t))}</button>`).join("")}`}
function matches(w){const q=state.search.trim().toLocaleLowerCase("ko"),x=[w.wine.name.ko,w.wine.name.en,w.wine.winery].filter(Boolean).join(" ").toLocaleLowerCase("ko"),f=state.filters;if(q&&!x.includes(q))return false;return(!f.type||w.wine.type===f.type)&&(!f.country||w.wine.country===f.country)&&(!f.region||w.wine.region===f.region)&&(!f.winery||w.wine.winery===f.winery)&&(!f.grape||w.wine.grapes.includes(f.grape))&&(!f.owned||(f.owned==="yes"?inventory(w)>0:inventory(w)===0));}
function nullable(a,b,d=1){const am=a==null||a==="",bm=b==null||b==="";if(am&&bm)return 0;if(am)return 1;if(bm)return-1;return(a>b?1:a<b?-1:0)*d}
function sorted(ws){const s={name:(a,b)=>a.wine.name.en.localeCompare(b.wine.name.en,"ko"),"purchase-desc":(a,b)=>nullable(latestPurchase(a)?.date,latestPurchase(b)?.date,-1),"price-desc":(a,b)=>nullable(latestPurchase(a)?.price.amount,latestPurchase(b)?.price.amount,-1),"price-asc":(a,b)=>nullable(latestPurchase(a)?.price.amount,latestPurchase(b)?.price.amount),"rating-desc":(a,b)=>nullable(latestRating(a),latestRating(b),-1)};return [...ws].sort(s[state.sort]??s.name)}
function card(w){const x=w.wine,p=latestPurchase(w),name=x.name.ko||x.name.en;return `<button class="wine-card" data-id="${escapeHtml(w.id)}"><div class="card-image">${imageMarkup(w)}<span class="card-status">${inventory(w)>0?`보유 ${inventory(w)}병`:"소비 완료"}</span></div><div class="card-body"><p class="card-kicker">${escapeHtml(x.winery)}</p><h3 class="wine-name">${escapeHtml(name)}</h3>${x.name.ko?`<p class="english-name wine-name">${escapeHtml(x.name.en)}</p>`:""}${wineIdentifiers(x)}<div class="card-facts"><span>${escapeHtml([x.country,x.region].filter(Boolean).join(" · "))}</span><span>${escapeHtml(typeLabels[x.type]??x.type)}</span></div><div class="card-footer"><div><span>최근 구매가</span><strong>${money(p?.price.amount)}</strong></div><div class="rating"><span>최근 내 평점</span><strong>${stars(latestRating(w))}</strong></div></div></div></button>`}
function list(w){const x=w.wine,p=latestPurchase(w),name=x.name.ko||x.name.en,origin=[x.country,x.region].filter(Boolean).join(" · ");return `<button class="wine-list-item" data-id="${escapeHtml(w.id)}"><div class="list-image">${imageMarkup(w)}</div><div class="list-main"><h3>${escapeHtml(name)}</h3>${wineIdentifiers(x)}<p>${escapeHtml([x.winery,origin].filter(Boolean).join(" · "))}</p></div><div><span>타입</span><strong>${escapeHtml(typeLabels[x.type]??x.type)}</strong></div><div><span>보유</span><strong>${inventory(w)}병</strong></div><div><span>최근 구매가</span><strong>${money(p?.price.amount)}</strong></div></button>`}
function fitCardNames(){$$(".wine-card .wine-name").forEach(e=>{e.classList.remove("compact-name");if(e.scrollWidth>=e.clientWidth)e.classList.add("compact-name")})}
function render(){const ws=sorted(state.wines.filter(matches));$("#result-count").textContent=`${ws.length} bottles`;$("#card-grid").innerHTML=ws.map(state.view==="grid"?card:list).join("");$("#card-grid").className=state.view==="grid"?"card-grid":"list-view";$("#empty-state").hidden=state.wines.length!==0;$("#no-results").hidden=state.wines.length===0||ws.length!==0;$("#card-grid").hidden=ws.length===0;$$("[data-id]",$("#card-grid")).forEach(e=>e.onclick=()=>openDetail(e.dataset.id));fitCardNames();}
const row=(l,v,wide=false,raw=false)=>`<div${wide?' class="wide"':""}><dt>${l}</dt><dd>${raw?v:escapeHtml(v)}</dd></div>`;
const optionalRow=(l,v,wide=false,raw=false)=>Array.isArray(v)?(v.length?row(l,v.join(" · "),wide,raw):""):(v===null||v===undefined||v===""?"":row(l,v,wide,raw));
const bottleDetails=b=>{const parts=[];if(b?.size)parts.push(readableBottleSize(b.size));if(b?.volumeMl!=null)parts.push(b.volumeMl>=1000?`${b.volumeMl/1000} L`:`${b.volumeMl} ml`);return parts.join(" · ")||null};
function history(items,kind){if(!items.length)return "<p class=\"muted\">기록 없음</p>";return `<div class="history">${[...items].sort((a,b)=>b.date.localeCompare(a.date)).map(i=>`<article><strong>${i.date} · ${i.quantity}병</strong><span>${escapeHtml(kind==="purchase"?`${text(i.store)} · ${money(i.price.amount)}`:text(i.note))}</span>${kind==="purchase"&&i.note?`<small>${escapeHtml(i.note)}</small>`:""}${i.review?`<div class="review"><b>${stars(i.review.rating)}</b><strong>${escapeHtml(text(i.review.title))}</strong>${i.review.content!==null?`<p>${escapeHtml(i.review.content)}</p>`:""}</div>`:""}</article>`).join("")}</div>`}
function openDetail(id){const w=state.wines.find(x=>x.id===id);if(!w)return;const x=w.wine,name=x.name.ko||x.name.en,vintage=vintageLabel(x),origin=[x.country,x.region].filter(Boolean).join(" · ");const wineInfo=[optionalRow("생산자",x.winery),optionalRow("타입",typeLabels[x.type]??x.type),optionalRow("국가",x.country),optionalRow("지역",x.region),optionalRow("아펠라시옹",x.appellation),optionalRow("등급",x.classification),optionalRow("빈티지",vintage),optionalRow("품종",x.grapes),optionalRow("도수",x.alcohol!=null?`${x.alcohol}%`:null),optionalRow("병 사이즈",bottleDetails(x.bottle)),optionalRow("당도",x.sweetness)].join("");const production=[optionalRow("양조 방식",x.productionMethod),optionalRow("숙성",x.aging)].join("");const serving=[optionalRow("권장 온도",x.servingTemperature),optionalRow("페어링",x.foodPairing)].join("");const vivino=x.vivino||{};const vivinoInfo=[optionalRow("평점",vivino.rating!=null?`${vivino.rating} / 5`:null),optionalRow("평가 수",vivino.ratingCount!=null?`${new Intl.NumberFormat("en-US").format(vivino.ratingCount)} ratings`:null),optionalRow("평균 가격",vivino.averagePrice!=null?money(vivino.averagePrice):null),vivino.url?row("Vivino 링크",`<a href="${escapeHtml(vivino.url)}" target="_blank" rel="noopener noreferrer">Vivino에서 보기 ↗</a>`,false,true):""].join("");$("#detail-content").innerHTML=`<div class="detail-hero"><div class="detail-image">${imageMarkup(w)}</div><div class="detail-summary">${x.winery?`<p class="card-kicker">${escapeHtml(x.winery)}</p>`:""}<h2 id="detail-title">${escapeHtml(name)}</h2>${x.name.ko?`<p class="english-name">${escapeHtml(x.name.en)}</p>`:""}<div class="detail-overview"><span>${escapeHtml([vintage,typeLabels[x.type]??x.type].filter(Boolean).join(" · "))}</span>${origin?`<span>${escapeHtml(origin)}</span>`:""}${x.appellation?`<span>${escapeHtml(x.appellation)}</span>`:""}</div></div></div>${x.description?`<div class="detail-description"><p>${escapeHtml(x.description)}</p></div>`:""}<div class="detail-sections"><section><h3>WINE INFORMATION</h3><dl>${wineInfo}</dl></section>${production?`<section><h3>PRODUCTION</h3><dl>${production}</dl></section>`:""}${serving?`<section><h3>SERVING</h3><dl>${serving}</dl></section>`:""}${vivinoInfo?`<section><h3>VIVINO</h3><dl>${vivinoInfo}</dl></section>`:""}<section><h3>MY COLLECTION</h3><dl>${row("현재 보유",`${inventory(w)}병`)}</dl>${history(w.purchases,"purchase")}</section><section class="wide-section"><h3>MY REVIEWS / CONSUMPTION</h3>${history(w.consumptions,"consumption")}</section></div>`;$("#detail-dialog").showModal();}
function updateQuickFilters(){$$('[data-type]').forEach(b=>b.setAttribute("aria-pressed",b.dataset.type===state.filters.type));$("#owned-toggle").setAttribute("aria-pressed",state.filters.owned==="yes")}
function filters(){const n=["country","region","winery","grape"].filter(k=>state.filters[k]).length;$("#filter-count").textContent=n;$("#filter-count").hidden=!n}
function resetFilters(){state.search="";state.filters={type:"",owned:"yes"};$("#search-input").value="";$$('[data-filter]').forEach(s=>s.value="");updateQuickFilters();filters();render()}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;localStorage.setItem("wineCollectionView",state.view);$$('[data-view]').forEach(q=>q.setAttribute("aria-pressed",q===b));render()});$("#search-input").oninput=e=>{state.search=e.target.value;render()};$("#sort-select").onchange=e=>{state.sort=e.target.value;render()};$("#filter-toggle").onclick=()=>{const p=$("#filter-panel");p.hidden=!p.hidden;$("#filter-toggle").setAttribute("aria-expanded",!p.hidden)};$(".type-quick-filters").onclick=e=>{const b=e.target.closest("[data-type]");if(!b)return;state.filters.type=b.dataset.type;updateQuickFilters();render()};$("#owned-toggle").onclick=()=>{state.filters.owned=state.filters.owned==="yes"?"":"yes";updateQuickFilters();render()};$$('[data-filter]').forEach(s=>s.onchange=e=>{state.filters[e.target.dataset.filter]=e.target.value;filters();render()});$("#reset-filters").onclick=$("#reset-search").onclick=resetFilters;$("#dialog-close").onclick=()=>$("#detail-dialog").close();window.addEventListener("resize",fitCardNames);document.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search-input").focus()}}}
async function load(){try{const r=await fetch(assetUrl("data/wines.json"),{cache:"no-store"});if(!r.ok)throw Error(r.status);state.wines=await r.json();if(!Array.isArray(state.wines))throw Error("Invalid JSON");state.view=localStorage.getItem("wineCollectionView")==="list"?"list":"grid";$$('[data-view]').forEach(b=>b.setAttribute("aria-pressed",b.dataset.view===state.view));updateStats();populateFilters();populateQuickFilters();render();$("#as-of").textContent=`총 ${state.wines.length}개의 기록`}catch(e){console.error(e);$("#error-state").hidden=false}finally{$("#loading-state").hidden=true}}
bind();load();
